[package]
name = "eruption-gui"
version = "0.0.11"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A GUI for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[features]
default = [] #["sourceview"]
sourceview = []

[dependencies]
cfg-if = "1.0.0"
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.102"
nix = "0.22.1"
rayon = "1.5.1"
walkdir = "2.3.2"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1.27"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.23"
config = "0.11.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
byteorder = "1.4.3"
itertools = "0.10.1"
lazy_static = "1.4.0"
palette = "0.6.0"
thiserror = "1.0.29"
eyre = "0.6.5"
color-eyre = "0.5.11"
paste = "1.0.5"
dbus = "0.9.3"
dbus-tokio = "0.7.4"
gdk-pixbuf = "0.14.0"
glib = "0.14.5"
pango = "0.14.3"
pangocairo = "0.14.0"
cairo-rs = "0.14.7"
#sourceview4 = { git = "https://gitlab.gnome.org/World/Rust/sourceview4-rs.git", branch = "master" }
icecream = "0.1.0"

[dependencies.gtk]
version = "0.14.1"
features = ["v3_22"]

[dependencies.gdk]
version = "0.14.2"
features = ["v3_22"]

[dependencies.gio]
version = "0.14.6"
features = ["v2_50"]

[dev-dependencies]
tokio = { version = "1.11.0", features = ["test-util"] }
