#    This file is part of Eruption.
#
#    Eruption is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Eruption is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Eruption.  If not, see <http://www.gnu.org/licenses/>.


[package]
name = "eruption-audio-proxy"
version = "0.0.5"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2021"
description = "Audio proxy daemon for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[dependencies]
cfg-if = "1.0.0"
clap =  { version = "3.0.12", features = ["derive"] }
clap_complete = "3.0.5"
serde = { version = "1.0.135", features = ["derive"] }
lazy_static = "1.4.0"
crossbeam = "0.8.1"
log = "0.4.14"
syslog = "6.0.1"
pretty_env_logger = "0.4.0"
libc = "0.2.113"
nix = "0.23.1"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
tokio = { version = "1.15.0", features = ["full"] }
socket2 = { version = "0.4.3", features = ["all"] }
ctrlc = { version = "3.2.1", features = ["termination"] }
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
thiserror = "1.0.30"
eyre = "0.6.6"
color-eyre = "0.6.0"
hound = "3.4.0"
bincode = "2.0.0-beta.2"
libpulse-binding = { version = "2.26.0", default-features = false }
libpulse-simple-binding = { version = "2.25.0", default-features = false }
rust-pulsectl = { git = "https://github.com/X3n0m0rph59/pulsectl.git", branch = "master" }
# dbus = "0.9.3"
# dbus-tree = "0.9.1"
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "0.9.0"
i18n-embed = { version = "0.13.1", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.1"
rust-embed = "6.3.0"
unic-langid = "0.9.0"
icecream = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.0.0"
tokio = { version = "1.15.0", features = ["test-util"] }

[build-dependencies]
prost-build = "0.9.0"
