[package]
name = "eruption-process-monitor"
version = "0.0.5"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A daemon to monitor and introspect system processes and events"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
async-trait = "0.1.48"
byteorder = "1.4.3"
clap =  { version = "3.0.0-beta.2", features = ["derive"] }
clap_generate = "3.0.0-beta.2"
ctrlc = { version = "3.1.8", features = ["termination"] }
config = "0.11.0"
colored = "2.0.0"
dbus = "0.9.2"
dbus-tokio = "0.7.3"
dbus-tree = "0.9.1"
dyn-clone = "1.0.4"
dyn-clonable = "0.9.0"
indexmap = "1.6.2"
log = "0.4.14"
libc = "0.2.92"
nix = "0.20.0"
pretty_env_logger = "0.4.0"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
regex = "1.4.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
tokio = { version = "1.4.0", features = ["full"] }
tracing = "0.1.25"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.17"
crossbeam = "0.8.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
thiserror = "1.0.24"
eyre = "0.6.5"
color-eyre = "0.5.10"
paste = "1.0.5"
hotwatch = "0.4.5"
hexdump = "0.1.1"
itertools = "0.10.0"
rayon = "1.5.0"
lazy_static = "1.4.0"
rust-crypto = "0.2.36"
procmon-sys = { version = "0.0.2", path = "src/procmon-sys" }
walkdir = "2.3.2"
x11rb = "0.8.1"

[dev-dependencies]
tokio = { version = "1.4.0", features = ["test-util"] }
