[package]
name = "eruption-process-monitor"
version = "0.0.10"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A daemon to monitor and introspect system processes and events"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[features]
default = ["sensors-most"]
sensors-most = ["procmon", "x11", "mutter"]
sensors-all = ["procmon", "x11", "wayland", "mutter"]
procmon = ["procmon-sys"]
x11 = ["x11rb"]
wayland = []
mutter = []

[dependencies]
cfg-if = "1.0.0"
async-trait = "0.1.51"
byteorder = "1.4.3"
clap =  { version = "3.0.0-beta.4", features = ["derive"] }
clap_generate = "3.0.0-beta.4"
ctrlc = { version = "3.2.0", features = ["termination"] }
config = "0.11.0"
dbus = "0.9.3"
dbus-tokio = "0.7.4"
dbus-tree = "0.9.1"
dyn-clone = "1.0.4"
dyn-clonable = "0.9.0"
indexmap = "1.7.0"
log = "0.4.14"
syslog = "5.0.0"
libc = "0.2.101"
nix = "0.22.1"
pretty_env_logger = "0.4.0"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
tokio = { version = "1.11.0", features = ["full"] }
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
crossbeam = "0.8.1"
toml = "0.5.8"
thiserror = "1.0.29"
eyre = "0.6.5"
color-eyre = "0.5.11"
hotwatch = "0.4.5"
lazy_static = "1.4.0"
walkdir = "2.3.2"
procmon-sys = { version = "0.0.2", path = "src/procmon-sys", optional = true }
x11rb = { version = "0.9.0", optional = true, features = ["allow-unsafe-code"] }

[dev-dependencies]
#icecream = "0.1.0"
tokio = { version = "1.11.0", features = ["test-util"] }
