#    This file is part of Eruption.
#
#    Eruption is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Eruption is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Eruption.  If not, see <http://www.gnu.org/licenses/>.


[package]
name = "eruption-process-monitor"
version = "0.0.11"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A daemon to monitor and introspect system processes and events"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[features]
default = ["sensors-most"]
sensors-most = ["procmon", "x11", "mutter"]
sensors-all = ["procmon", "x11", "wayland", "mutter"]
procmon = ["procmon-sys"]
x11 = ["x11rb"]
wayland = []
mutter = []

[dependencies]
cfg-if = "1.0.0"
async-trait = "0.1.51"
byteorder = "1.4.3"
clap =  { version = "3.0.0-beta.5", features = ["derive"] }
clap_generate = "3.0.0-beta.5"
ctrlc = { version = "3.2.1", features = ["termination"] }
config = "0.11.0"
dbus = "0.9.5"
dbus-tokio = "0.7.5"
dbus-tree = "0.9.2"
dyn-clone = "1.0.4"
dyn-clonable = "0.9.0"
indexmap = "1.7.0"
log = "0.4.14"
syslog = "5.0.0"
libc = "0.2.106"
nix = "0.23.0"
pretty_env_logger = "0.4.0"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.13.0", features = ["full"] }
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
crossbeam = "0.8.1"
toml = "0.5.8"
thiserror = "1.0.30"
eyre = "0.6.5"
color-eyre = "0.5.11"
hotwatch = "0.4.6"
lazy_static = "1.4.0"
walkdir = "2.3.2"
procmon-sys = { version = "0.0.2", path = "src/procmon-sys", optional = true }
x11rb = { version = "0.9.0", optional = true, features = ["allow-unsafe-code"] }
i18n-embed = { version = "0.13.0", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.0"
rust-embed = "6.2.0"
unic-langid = "0.9.0"

[dev-dependencies]
icecream = "0.1.0"
pretty_assertions = "1.0.0"
tokio = { version = "1.13.0", features = ["test-util"] }
