[package]
name = "eruption-util"
version = "0.0.6"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI developer support utility for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[dependencies]
cfg-if = "1.0.0"
clap =  { version = "3.0.0-beta.5", features = ["derive"] }
clap_generate = "3.0.0-beta.5"
ctrlc = { version = "3.2.1", features = ["termination"] }
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.104"
nix = "0.23.0"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
tokio = { version = "1.12.0", features = ["full"] }
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
crossbeam = "0.8.1"
thiserror = "1.0.30"
eyre = "0.6.5"
color-eyre = "0.5.11"
hexdump = "0.1.1"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.6.2"
evdev-rs = "0.5.0"
lazy_static = "1.4.0"
bitvec = "0.22.3"


[dev-dependencies]
icecream = "0.1.0"
pretty_assertions = "1.0.0"
tokio = { version = "1.12.0", features = ["test-util"] }
