[package]
name = "eruption-util"
version = "0.0.5"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI developer support utility for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
clap =  { version = "3.0.0-beta.2", features = ["derive"] }
clap_generate = "3.0.0-beta.2"
ctrlc = { version = "3.1.9", features = ["termination"] }
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.98"
nix = "0.22.0"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.8.1", features = ["full"] }
tracing = "0.1.26"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.19"
crossbeam = "0.8.1"
thiserror = "1.0.26"
eyre = "0.6.5"
color-eyre = "0.5.11"
paste = "1.0.5"
hexdump = "0.1.1"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.6.2"
evdev-rs = "0.5.0"
lazy_static = "1.4.0"
bitvec = "=0.19.5"

[dev-dependencies]
tokio = { version = "1.8.1", features = ["test-util"] }
