[package]
name = "eruption-netfx"
version = "0.0.2"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A Network FX protocol client for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
# async-std = { version = "1.6.2", features = ["attributes", "tokio02"] }
# async-macros = "2.0.0"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
colored = "2.0.0"
log = "0.4.13"
pretty_env_logger = "0.4.0"
libc = "0.2.82"
nix = "0.19.1"
rayon = "1.5.0"
walkdir = "2.3.1"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = { version = "1.0.61" }
tokio = { version = "1.0.2", features = ["full"] }
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
thiserror = "1.0.23"
eyre = "0.6.5"
color-eyre = "0.5.10"
num-traits = "0.2.14"
image = "0.23.12"
x11 = { version = "2.18.2", features = ["xlib", "xrandr"] }

[dev-dependencies]
tokio = { version = "1.0.2", features = ["test-util"] }
