[package]
name = "eruption-netfx"
version = "0.0.4"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A Network FX protocol client for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
clap =  { version = "3.0.0-beta.2", features = ["derive"] }
clap_generate = "3.0.0-beta.2"
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.93"
nix = "0.20.0"
rayon = "1.5.0"
walkdir = "2.3.2"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.4.0", features = ["full"] }
tracing = "0.1.25"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.17"
thiserror = "1.0.24"
eyre = "0.6.5"
color-eyre = "0.5.10"
num-traits = "0.2.14"
image = "0.23.14"
x11 = { version = "2.18.2", features = ["xlib", "xrandr"] }

[dev-dependencies]
tokio = { version = "1.4.0", features = ["test-util"] }
