[package]
name = "eruption-netfx"
version = "0.0.6"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A Network FX protocol client for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[dependencies]
cfg-if = "1.0.0"
clap =  { version = "3.0.0-beta.4", features = ["derive"] }
clap_generate = "3.0.0-beta.4"
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.102"
rayon = "1.5.1"
walkdir = "2.3.2"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
tokio = { version = "1.11.0", features = ["full"] }
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
thiserror = "1.0.29"
eyre = "0.6.5"
color-eyre = "0.5.11"
num-traits = "0.2.14"
image = "0.23.14"
x11 = { version = "2.18.2", features = ["xlib", "xrandr"] }

[dev-dependencies]
#icecream = "0.1.0"
tokio = { version = "1.11.0", features = ["test-util"] }
