[package]
name = "eruption-debug-tool"
version = "0.0.13"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI utility to debug USB HID devices"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
crossbeam = "0.8.0"
clap =  { version = "3.0.0-beta.2", features = ["derive"] }
clap_generate = "3.0.0-beta.2"
colored = "2.0.0"
ctrlc = { version = "3.1.9", features = ["termination"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.93"
nix = "0.20.0"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.5.0", features = ["full"] }
tracing = "0.1.25"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.17"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
thiserror = "1.0.24"
eyre = "0.6.5"
color-eyre = "0.5.11"
paste = "1.0.5"
hexdump = "0.1.1"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.6.2"
bitvec = "=0.19.5"
serialport = "4.0.1"
icecream = "0.1.0"

[dev-dependencies]
tokio = { version = "1.5.0", features = ["test-util"] }
