[package]
name = "eruption-debug-tool"
version = "0.0.5"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI utility to debug USB HID devices"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
# async-std = { version = "1.6.2", features = ["attributes", "tokio02"] }
# async-macros = "2.0.0"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
colored = "2.0"
log = "0.4.13"
pretty_env_logger = "0.4.0"
libc = "0.2.82"
nix = "0.19.1"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = { version = "1.0.61" }
tokio = { version = "1.0.2", features = ["full"] }
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
thiserror = "1.0.23"
eyre = "0.6.5"
color-eyre = "0.5.10"
paste = "1.0"
hexdump = "0.1.0"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.5.1"

[dev-dependencies]
tokio = { version = "1.0.2", features = ["test-util"] }
