[package]
name = "eruption-debug-tool"
version = "0.0.15"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI utility to debug USB HID devices"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[dependencies]
lazy_static = "1.4.0"
cfg-if = "1.0.0"
crossbeam = "0.8.1"
clap =  { version = "3.0.0-beta.4", features = ["derive"] }
clap_generate = "3.0.0-beta.4"
colored = "2.0.0"
ctrlc = { version = "3.2.0", features = ["termination"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.102"
nix = "0.22.1"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.12.0", features = ["full"] }
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
thiserror = "1.0.29"
eyre = "0.6.5"
color-eyre = "0.5.11"
hexdump = "0.1.1"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
bitvec = "0.22.3"
byteorder = "1.4.3"
serialport = "4.0.1"
crc8 = "0.1.1"

[dev-dependencies]
icecream = "0.1.0"
pretty_assertions = "0.7.2"
tokio = { version = "1.12.0", features = ["test-util"] }
