[package]
name = "eruption"
version = "0.1.23"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "Eruption Linux user-mode input and LED driver for keyboards, mice and other devices"
repository = "https://github.com/X3n0m0rph59/eruption.git"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[dependencies]
cfg-if = "1.0.0"
crossbeam = "0.8.1"
futures = "0.3.17"
parking_lot = { version = "0.11.2", features = ["deadlock_detection"] }
async-trait = "0.1.51"
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
libc = "0.2.101"
nix = "0.22.1"
log = "0.4.14"
syslog = "5.0.0"
pretty_env_logger = "0.4.0"
thiserror = "1.0.29"
eyre = "0.6.5"
color-eyre = "0.5.11"
toml = "0.5.8"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
tokio = { version = "1.11.0", features = ["full", "rt-multi-thread"] }
ctrlc = { version = "3.2.0", features = ["termination"] }
clap = "3.0.0-beta.4"
hotwatch = "0.4.5"
config = "0.11.0"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.6.2"
evdev-rs = "0.5.0"
hexdump = "0.1.1"
byteorder = "1.4.3"
itertools = "0.10.1"
rayon = "1.5.1"
lazy_static = "1.4.0"
rand = "0.8.4"
csscolorparser = "0.5.0"
colorgrad = "0.5.0"
palette = "0.6.0"
nalgebra = "0.29.0"
noise = "0.7.0"
simdnoise = "3.1.6"
mlua = { version = "0.6.2", features = ["luajit"] }
mlua_derive = "0.6.0"
sysinfo = "0.20.3"
procinfo = "0.4.2"
rustfft = "6.0.1"
hound = "3.4.0"
libpulse-binding = { version = "2.25.0", default-features = false }
libpulse-simple-binding = { version = "2.24.1", default-features = false }
rust-pulsectl = { git = "https://github.com/X3n0m0rph59/pulsectl.git", branch = "master" }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
dbus = "0.9.3"
dbus-tree = "0.9.1"
paste = "1.0.5"
bitvec = "0.22.3"
serialport = "4.0.1"

# ubuntu bionic
# sysinfo = "=0.14.2"

[dev-dependencies]
#icecream = "0.1.0"
thiserror = "1.0.29"
tokio = { version = "1.11.0", features = ["test-util"] }
