[package]
name = "eruptionctl"
version = "0.0.2"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI control utility for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
# async-std = { version = "1.6.2", features = ["attributes", "tokio02"] }
# async-macros = "2.0.0"
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
colored = "2.0.0"
log = "0.4.11"
libc = "0.2.81"
nix = "0.19.1"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = { version = "1.0.61" }
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
toml = "0.5.8"
thiserror = "1.0.23"
eyre = "0.6.4"
color-eyre = "0.5.10"
paste = "1.0.4"
dbus = "0.9.0"
dbus-tokio = "0.6.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["test-util"] }
