[package]
name = "eruptionctl"
version = "0.0.8"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI control utility for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[dependencies]
clap =  { version = "3.0.0-beta.2", features = ["derive"] }
clap_generate = "3.0.0-beta.2"
colored = "2.0.0"
log = "0.4.14"
libc = "0.2.98"
nix = "0.22.0"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.8.1", features = ["full"] }
tracing = "0.1.26"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.19"
config = "0.11.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
thiserror = "1.0.26"
eyre = "0.6.5"
color-eyre = "0.5.11"
paste = "1.0.5"
dbus = "0.9.3"
dbus-tokio = "0.7.3"

[dev-dependencies]
tokio = { version = "1.8.1", features = ["test-util"] }
